#server:
#  port: 8080
spring:
  application:
    name: producer-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address:  192.168.56.1
#    hostname: app-client-01